Method: 'FMM'

Sky:
    CMB:

        cmb: True
        r: [0, 'f', 'r', 0.036]
        Alens: [1, 'nf', 'A_{lens}', 1]

    Foregrounds:

        # Thermal Dust emission
        Dust: False
        nu0_d: 353
        Ad: [4, 'nf', 'A_d']
        betad: [1.54, 'nf', '\beta_d']
        alphad: [-0.4, 'nf', '\alpha_d']
        deltad: [1, 'nf', '\Delta_d']

        # Synchrotron emission
        Synchrotron: False
        nu0_s: 23
        As: [0, 'nf', 'A_s']
        betas: [-3, 'nf', '\beta_s']
        alphas: [-0.4, 'nf', '\alpha_s']
        deltas: [1, 'nf', '\Delta_s']
        DustSync: False
        eps: [0, 'nf', '\varepsilon']

    nside: 128

QUBIC:
    npointings: 1000
    nsub: 4
    nrec: 2
    seed: 0
    iteration: 1
    ndet: 1
    npho150: 1
    npho220: 1
    synthbeam_kmax: 1
    detector_nep: 4.7e-17
    nhwp_angles: 3
    dtheta: 15
    type: 'two'
    covcut: 0.2
    kappa: 0
    convolution: False
    bandpass_correction: True
    RA_center: 0
    DEC_center: -57
    dust_model: 'd0'
    sync_model: 's0'

Spectrum:
    do_spectrum: True
    method: 'namaster'
    dl: 30
    lmin: 40
    aposize: 10
    beam_correction: False
    pixwin_correction: False
    noise_correction: True
    nbins: 5

PCG:
    maxiter: 200
    tol: 1.0e-20
    gif: True

Sampler:
    do_sampler: True
    nsteps: 200
    nwalkers: 10
    ndim: 1
    discard: 100
    markers: False
    sig_initial_guess: 0.01
    title_limit: 1

Data:
    datafilename: 'ggg'
    planck: 
        30GHz: False
        44GHz: False
        70GHz: False
        100GHz: False
        143GHz: False
        217GHz: False
        353GHz: False
    level_planck_noise: 0
    use_external_data: True

