path_out: 'mytest_to_remove/'

Sky:
    CMB:

        cmb: [True, 1]
        r: 0
        Alens: 1

    Foregrounds:

        # Thermal Dust emission
        Dust: False
        # Synchrotron emission
        Synchrotron: False

    nside: 256

QUBIC:
    npointings: 80
    fsub: 2
    nrec: 2
    iteration: 1
    ndet: 1
    npho150: 1
    npho220: 1
    synthbeam_kmax: 1
    detector_nep: 4.7e-17
    nhwp_angles: 3
    dtheta: 15
    type: 'two'
    covcut: 0.2
    kappa: 0
    convolution: False
    bandpass_correction: True
    RA_center: 0
    DEC_center: -57

Spectrum:
    dl: 30
    lmin: 40
    lmax: 511
    aposize: 10

PCG:
    maxiter: 4
    tol: 1.0e-20

Data:
    datafilename: 'MC'
    planck: True
    level_external_data_noise: 1

Pipeline:
    mapmaking: True
    spectrum: True

