path_out: 'E2E_nrec2/cmbdust_convolution_fixext_DB/'

Sky:
    CMB:

        cmb: [True, 1]
        r: 0
        Alens: 1

    Foregrounds:

        # Thermal Dust emission
        Dust: True
        # Synchrotron emission
        Synchrotron: False

    nside: 256

QUBIC:
    npointings: 8000
    fsub: 4
    nrec: 2
    iteration: 1
    ndet: 1
    npho150: 1
    npho220: 1
    synthbeam_kmax: 1
    detector_nep: 4.7e-17
    nhwp_angles: 3
    dtheta: 15
    type: 'two'
    covcut: 0.2
    kappa: 0
    convolution: True
    reconvolution_after_MM: False
    bandpass_correction: True
    RA_center: 0
    DEC_center: -57

Spectrum:
    dl: 30
    lmin: 40
    lmax: 511
    aposize: 10

PCG:
    maxiter: 400
    tol: 1.0e-20

Data:
    datafilename: 'MC'
    planck: True
    level_external_data_noise: 1

Pipeline:
    mapmaking: True
    spectrum: True

bandwidth_qubic: 0.25
bandwidth_planck: 0.2
nb_integration: 100

