Method: 'FMM'

Sky:
    CMB:
        cmb: False
        r: [0, 'f', 'r', 0.001]
        Alens: [1, 'f', 'A_{lens}', 1]

    Foregrounds:
        # Thermal Dust emission
        Dust: True
        # Synchrotron emission
        Synchrotron: False
        

    nside: 64

QUBIC:
    #method: 'MM'   
    #randomreal: True
    npointings: 1000
    nsub: 4
    nrec: 2
    seed: 0
    #iteration: 1
    ndet: 1
    npho150: 1
    npho220: 1
    synthbeam_kmax: 1
    detector_nep: 4.7e-17
    nhwp_angles: 3
    dtheta: 15
    type: 'two'
    covcut: 0.10
    kappa: 0
    convolution: False
    bandpass_correction: True
    RA_center: 0
    DEC_center: -57
    dust_model: 'd0'
    sync_model: 's0'
    #fsky: 0.035
    level_planck_noise: 1

PCG:
    maxiter: 300
    tol: 1.0e-20

Data:
    datafilename: 'MC'

