path_out: 'test_QU_only'

Sky:
    CMB:

        cmb: [True, 1]
        r: 0
        Alens: 1

    Foregrounds:

        # Thermal Dust emission
        Dust: True
        # Synchrotron emission
        Synchrotron: False

    nside: 64

QUBIC:
    npointings: 2000
    fsub: 4
    nrec: 2
    iteration: 1
    ndet: 1
    npho150: 1
    npho220: 1
    synthbeam_kmax: 1
    detector_nep: 4.7e-17
    nhwp_angles: 3
    dtheta: 15
    type: 'two'
    covcut: 0.2
    kappa: 0
    convolution: False
    reconvolution_after_MM: False
    bandpass_correction: True
    RA_center: 0
    DEC_center: -57
    planck_regularization: False

Spectrum:
    dl: 30
    lmin: 40
    lmax: 511
    aposize: 10

PCG:
    maxiter: 100
    tol: 1.0e-20

Data:
    datafilename: 'MC'
    planck: True
    level_external_data_noise: 1

Pipeline:
    mapmaking: True
    spectrum: False

bandwidth_qubic: 0.25
bandwidth_planck: 0.2
nb_integration: 100

#python main.py E2E_nrec1/maps/MC_10046631.pkl
#python main.py E2E_nrec2/cmb_convolved_UWB/maps/MC_7721231.pkl