Method: 'FMM'

Sky:
    CMB:

        cmb: True
        r: [0, 'f', 'r', 0.001]
        Alens: [1, 'f', 'A_{lens}', 1]

    Foregrounds:

        # Thermal Dust emission
        Dust: True
        nu0_d: 353
        Ad: [4, 'f', 'A_d', 4]
        betad: [1.54, 'f', '\beta_d', 1.54]
        alphad: [-0.4, 'f', '\alpha_d', -0.4]
        deltad: [1, 'f', '\Delta_d', 1]

        # Synchrotron emission
        Synchrotron: False
        nu0_s: 23
        As: [0, 'nf', 'A_s']
        betas: [-3, 'nf', '\beta_s']
        alphas: [-0.4, 'nf', '\alpha_s']
        deltas: [1, 'nf', '\Delta_s']
        DustSync: False
        eps: [0, 'nf', '\varepsilon']

    nside: 256

QUBIC:
    method: 'spec'                                 # 'MM' for QUBIC map-making, 'fake' for fake map-making, 'spec' for spectrum based
    randomreal: True
    npointings: 1000
    nsub: 4
    nrec: 2
    seed: 0
    iteration: 1
    ndet: 1
    npho150: 1
    npho220: 1
    synthbeam_kmax: 1
    detector_nep: 4.7e-17
    nhwp_angles: 3
    dtheta: 15
    type: 'two'
    covcut: 0.2
    kappa: 0
    convolution: False
    bandpass_correction: True
    RA_center: 0
    DEC_center: -57
    dust_model: 'd0'
    sync_model: 's0'
    fsky: 0.035

Spectrum:
    do_spectrum: False
    method: 'namaster'
    dl: 30
    lmin: 40
    aposize: 10
    beam_correction: False
    pixwin_correction: False
    noise_correction: True
    nbins: 10

PCG:
    maxiter: 100
    tol: 1.0e-20
    gif: True

Sampler:
    do_sampler: True
    nsteps: 300
    N: 5
    ndim: 6
    discard: 200
    markers: False
    sig_initial_guess: 0.01
    title_limit: 1

Data:
    datafilename: 'ggg'
    planck: 
        30GHz: False
        44GHz: False
        70GHz: False
        100GHz: False
        143GHz: False
        217GHz: False
        353GHz: True
    level_planck_noise: 0
    use_external_data: True

