<<<<<<< HEAD
path_out: '/pbs/home/t/tlaclave/sps/FMM_data/test/'
datafilename: 'MC'

=======
>>>>>>> 7bb924e5da7a9bcf3eef73b84e6af68fc9377d03
CMB:
    cmb: True
    seed: 1                                    # CMB realization
    r: 0
    Alens: 1
 
Foregrounds:
 
    ### This section define the in/out foregrounds contribution

    fit_spectral_index: False                    # If False, the beta reconstruction is skipped
    bin_mixing_matrix: 4
    blind_method: 'minimize'                    # Fit the mixing matrix with different methods when all the components are fitted with blind method: 'PCG', 'alternate' or 'minimize'

    # Thermal Dust emission
    Dust:
        Dust_in: True
        Dust_out: True

        type: 'parametric'                           # Reconstruction method
        model_d: 'd0'
        beta_d_init: [1.54, 0]                  # PySM model
        nside_beta_in: 0                        # Input pixelization for beta_d (in a case of d1 model)
        nside_beta_out: 0                       # Output pixelization for beta_d (in a case of d1 model)
        nu0_d: 150                              # Reference frequency (nu0_d)
        l_corr: 7                              # Decorrelation level (seen only with d6 model)
        amplification_d: 1                      # Amplification of the dust contribution
    
    # Synchrotron emission
    Synchrotron:
        Synchrotron_in: False
        Synchrotron_out: False

        type: 'parametric'                      # Reconstruction method
        model_s: 's0'                           # PySM model
        beta_s_init: [-3, 0]
        nu0_s: 150                             # Reference frequency (nu0_s)
        amplification_s: 1                             # Amplification of the synchrotron contribution

    # CO line emission
    CO:
        CO_in: False
        CO_out: False
        nu0_co: 230.538
        polarization_fraction: 0.01                     # Polarization fraction

QUBIC:

    ### This section control the parameters related to QUBIC

    instrument: 'DB'                        # Instrumental design (DB or UWB)
    npointings: 1000                        # Number of time samples
    nsub_in: 50
    nsub_out: 20                                # Number of sub-acquisitions
    nrec: 2                                 # Number of reconstructed frequency maps
    convolution_in: True                   # Angular resolution in the input TOD
    convolution_out: True                  # Angular resolution in the reconstruction
    bandpass_correction: True               # Correction to keep the edges of the integration band constant
    NOISE:                          
        ndet: 0                             # Level of detector noise
        npho150: 0                          # Level of photon noise at 150 GHz
        npho220: 0                          # Level of photon noise at 220 GHz
        detector_nep: 4.7e-17                 # NEP of detector noise
    SYNTHBEAM:
        synthbeam_kmax: 1                  # Order of synthesized beam diffraction (synthbeam_kmax = 1 means 9 peaks)
        synthbeam_fraction: 1              # Fraction of synthesized beam
    dtheta: 15                             # Angle for coverage
    GAIN:
        sig_gain: 0                        # Standard deviation for input detector gains
        fit_gain: False                    # Fitting gain detectors

SKY:

    ### This section control the reconstructed sky

<<<<<<< HEAD
    nside: 128                              # Nside of components
    coverage_cut: 0.2                      # Define a cut where the coverage is too low
=======
    nside: 64                              # Nside of components
>>>>>>> 7bb924e5da7a9bcf3eef73b84e6af68fc9377d03
    RA_center: 0                   
    DEC_center: -45


PLANCK:

    ### This section define which external data are we using

<<<<<<< HEAD
    external_data: False                         
    weight_planck: 0                            # Weight of Planck data within the QUBIC patch
    level_noise_planck: 1                       # Noise level for Planck data
    bandwidth_planck: 0.2                       # Multiplicative factor to define the bandwidth of Planck's data
    nsub_planck: 100                            # Number of sub acquisitions for Planck's data

Pipeline:
    mapmaking: True                              # Run MapMaking Pipeline
    spectrum: False                              # Compute Power Spectra of the frequency maps
=======
    level_noise_planck: 1                         # Noise level for Planck data
    nintegr_planck: 1                             # Number of integration step for Planck data
    thr_planck: 0                               # Threashold to remove planck weight within QUBIC patch
    weight_planck: 0                              # Weight of Planck data within the QUBIC patch
    fwhm_weight_planck: 0                         # FWHM for apodized QUBIC patch
    30GHz: False
    44GHz: False
    70GHz: False
    100GHz: False
    143GHz: False
    217GHz: False
    353GHz: True
>>>>>>> 7bb924e5da7a9bcf3eef73b84e6af68fc9377d03

PCG:

    ### This section control PCG parameters

<<<<<<< HEAD
    n_iter_pcg: 50                                   # Number of PCG iterations
    tol_pcg: 1.0e-12                                # Tolerance for PCG

Spectrum:

    ### This section define the parameters to compute the power spectra

    dl: 30                                      
    lmin: 40
    lmax: 511
=======
    n_iter_pcg: 10                                   # Number of PCG iterations
    tol_pcg: 1.0e-20                                # Tolerance for PCG
    n_iter_loop: 2                                  # Number of loop (1 loop is PCG + beta fitting + gain reconstruction)
    ites_to_converge: 1                            # should be less than k
    tol_rms: 1.0e-10
    fix_pixels_outside_patch: True         # Fixing pixels outside QUBIC patch
    fixI: False                             # Fix the intensity during the map-making

INITIAL:

    ### This section control the initialization of the components 
    
    fwhm0: 0 #.0078                  # Convolution kernel for the initial guess maps
    sig_map_noise: 0          # Standard deviation of noise in first guess maps
    qubic_patch_cmb: 0        # Multiplicative factor of initial CMB within the QUBIC patch
    qubic_patch_dust: 0       # Multiplicative factor of initial Dust within the QUBIC patch
    qubic_patch_sync: 1       # Multiplicative factor of initial Sync within the QUBIC patch
    qubic_patch_co: 1         # Multiplicative factor of initial CO within the QUBIC patch

SPECTRUM:
    lmin: 10
    dl: 30
>>>>>>> 7bb924e5da7a9bcf3eef73b84e6af68fc9377d03
    aposize: 10

Plots:
    conv_beta: True           # Plot spectral indices convergence 
    conv_gain: False          # Plot gain convergence 
    conv_rms: True            # Plot RMS convergence 
    maps: True                # Plot maps convergence 
    thr_plot: 0.2             # Threashold for maps plot

save_iter: 1                                    # Save every 'save_iter' iteration
foldername: 'test_to_remove_cmm_blind'          # Name of the saved folder
filename: 'file'                                # Name of the saved file
lastite: True                                   # Keep only the last iteration 
