data:
  path : '/sps/qubic/Users/TomLaclavere/Pipeline/'
  n_real : 40

simu: 
  nrec : 2
  qubic_config : UWB
  name : 'Sky'
  noise : True

MCMC:
  nwalkers : 50
  mcmc_steps : 500
  discard : 200
  stretch_move_factor : 0.7
  snooker_move_gamma : 1.7

SKY_PARAMETERS:
  r : [True, 0, 1, -10, 10] 
  Alens : [1, 0, 1, 0, 1]
  nu0_d : [353, 0, 1, 0, 1000]
  Ad : [True, 10, 1, 0, 20]
  alphad : [True, 0, 1, -10, 10]
  betad : [1.54, 0, 1, 1.3, 1.7]
  deltad : [1, 0, 1, 0, 1000]