data:
  path : '/pbs/home/t/tlaclave/sps/Pipeline/spectra/with_convolution_DB_Nrec=2_spectra'
  n_real : 200
  pipeline : 'FMM'

simu: 
  nrec : 2
  qubic_config : DB
  noise : True
  name : 'Sky'

MCMC:
  nwalkers : 50
  mcmc_steps : 1000
  discard : 250
  stretch_move_factor : 0.7
  snooker_move_gamma : 1.7
  thin : 15

NS:
  DynamicNS : True
  nlive : 500
  prior_transform : 'uniform'
  bound : 'multi'
  queue_size : 16

SKY_PARAMETERS:
  r : [True, 0, 1, 0, 1] 
  Alens : [1, 0, 1, 0, 1]
  nu0_d : [353, 0, 1, 0, 1000]
  Ad : [True, 0, 20, 0, 20]
  alphad : [True, 10, 20, -10, 10]
  betad : [1.54, 0, 1, 1.3, 1.7]
  deltad : [1, 0, 1, 0, 1000]

Method : 'NS'