data:
  path_out : '/pbs/home/t/tlaclave/sps/Pipeline/spectra/with_convolution/UWB_Nrec=2_spectra_test/'
  path_noise : '/pbs/home/t/tlaclave/sps/Pipeline/data_with_convolution/UWB_Nrec=2_Noise'
  path_sky : '/pbs/home/t/tlaclave/sps/Pipeline/data_with_convolution/UWB_Nrec=2_Sky'
  pipeline : 'FMM'

simu: 
  nrec : 2
  qubic_config : UWB

Spectrum:
  lmin : 40
  dl : 30
  nbins : 16